/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_korizza_colorizer_io_ColorizerNative */

#ifndef _Included_org_korizza_colorizer_io_ColorizerNative
#define _Included_org_korizza_colorizer_io_ColorizerNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_korizza_colorizer_io_ColorizerNative
 * Method:    colorize
 * Signature: (Ljava/lang/String;)[I
 */
JNIEXPORT jintArray JNICALL Java_org_korizza_colorizer_io_ColorizerNative_colorize
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_korizza_colorizer_io_ColorizerNative
 * Method:    test
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_korizza_colorizer_io_ColorizerNative_test
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
